// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UkwhwtMWYoyRCn3aNDmYi8dtXFAwgJg',
    appId: '1:211905121598:web:31d96c584291a4c7dab06f',
    messagingSenderId: '211905121598',
    projectId: 'zenora-99e7f',
    authDomain: 'zenora-99e7f.firebaseapp.com',
    storageBucket: 'zenora-99e7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexp9vmZcRKzVt70tmJ8AhlQOp1h9i2fw',
    appId: '1:211905121598:android:0a397694e90e0063dab06f',
    messagingSenderId: '211905121598',
    projectId: 'zenora-99e7f',
    storageBucket: 'zenora-99e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN14--mz6hbWglEJq46NYvhLDSj0pqbw8',
    appId: '1:211905121598:ios:24e2449e8ae5dc17dab06f',
    messagingSenderId: '211905121598',
    projectId: 'zenora-99e7f',
    storageBucket: 'zenora-99e7f.firebasestorage.app',
    iosBundleId: 'com.example.zenora2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN14--mz6hbWglEJq46NYvhLDSj0pqbw8',
    appId: '1:211905121598:ios:24e2449e8ae5dc17dab06f',
    messagingSenderId: '211905121598',
    projectId: 'zenora-99e7f',
    storageBucket: 'zenora-99e7f.firebasestorage.app',
    iosBundleId: 'com.example.zenora2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0UkwhwtMWYoyRCn3aNDmYi8dtXFAwgJg',
    appId: '1:211905121598:web:398ea5987adffef0dab06f',
    messagingSenderId: '211905121598',
    projectId: 'zenora-99e7f',
    authDomain: 'zenora-99e7f.firebaseapp.com',
    storageBucket: 'zenora-99e7f.firebasestorage.app',
  );
}
